import Head from 'next/head';

const Layout = ({ children, global, pageContext }) => {
  console.log(pageContext);
  return (
    <>
      <Head>
        <title>O Jeju Jeju</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default Layout;
